# Generated by Django 4.1.5 on 2023-02-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_category_name_alter_subcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'подкатегория', 'verbose_name_plural': 'подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'инструмент', 'verbose_name_plural': 'инструменты'},
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='subcategories',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(upload_to='category_image', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='picture',
            field=models.ImageField(upload_to='subcategory_image', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='picture',
            field=models.ImageField(upload_to='tool_image', verbose_name='Фото'),
        ),
    ]
