# Generated by Django 4.1.5 on 2023-03-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(verbose_name='Отзыв'),
        ),
    ]
