# Generated by Django 4.1.5 on 2024-02-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Проверен'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(verbose_name='Отзыв'),
        ),
    ]
