# Generated by Django 4.1.5 on 2023-03-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Проверен'),
        ),
    ]
